// Wygenerowane przez tools/import-slowka.js — nie edytuj ręcznie.
window.SEED_WORDS = [
 {
  "id": "good afternoon!",
  "en": "Good afternoon!",
  "pl": "Dzień dobry! (po południu)",
  "pron": "[gud af-ter-NUN]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "after = po + noon = południe → dosłownie „po-południe”",
  "example": "Good afternoon, Mrs Brown!",
  "added": "2026-09-26"
 },
 {
  "id": "good evening!",
  "en": "Good evening!",
  "pl": "Dobry wieczór!",
  "pron": "[gud IW-nyng]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "Eve(ning) — kolacja z Ewą wieczorem",
  "example": "Good evening, Tom!",
  "added": "2026-09-26"
 },
 {
  "id": "good morning!",
  "en": "Good morning!",
  "pl": "Dzień dobry! (rano)",
  "pron": "[gud MOR-nyng]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "morning = ranek — „mroczno” jeszcze rano",
  "example": "Good morning, Anna!",
  "added": "2026-09-26"
 },
 {
  "id": "good to see you!",
  "en": "Good to see you!",
  "pl": "Dobrze cię widzieć!",
  "pron": "[gud tu SI ju]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "see = widzieć — jak sea (morze): patrzysz na morze",
  "example": "Hi, Tom! Good to see you!",
  "added": "2026-09-26"
 },
 {
  "id": "hello!",
  "en": "Hello!",
  "pl": "Dzień dobry! / Cześć!",
  "pron": "[he-LOU]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "„halo” jak przy odbieraniu telefonu",
  "example": "Hello! I'm Michal.",
  "added": "2026-09-25"
 },
 {
  "id": "hey!",
  "en": "Hey!",
  "pl": "Hej! (bardzo luźno)",
  "pron": "[hej]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "to samo co polskie „hej”",
  "example": "Hey, Tom!",
  "added": "2026-09-26"
 },
 {
  "id": "hi there!",
  "en": "Hi there!",
  "pl": "Cześć! (luźno, do kilku osób też)",
  "pron": "[haj DER] ⚠️ th",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "there = tam → „hej tam!”",
  "example": "Hi there! I'm Anna.",
  "added": "2026-09-26"
 },
 {
  "id": "hi!",
  "en": "Hi!",
  "pl": "Cześć! (przywitanie)",
  "pron": "[haj]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "krótkie „haj” = machnięcie ręką",
  "example": "Hi, Tom!",
  "added": "2026-09-25"
 },
 {
  "id": "long time no see!",
  "en": "Long time no see!",
  "pl": "Kopę lat!",
  "pron": "[long tajm nou SI]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "dosłownie „długo nie widzieć” — łamany angielski, dlatego łatwy",
  "example": "Hi, Tom! Long time no see!",
  "added": "2026-09-26"
 },
 {
  "id": "welcome!",
  "en": "Welcome!",
  "pl": "Witaj! / Witamy!",
  "pron": "[ŁEL-kam]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "well + come = dobrze, że przyszedłeś",
  "example": "Welcome, Anna!",
  "added": "2026-09-26"
 },
 {
  "id": "what's up?",
  "en": "What's up?",
  "pl": "Co tam? (bardzo luźno)",
  "pron": "[łots AP]",
  "pos": "zwrot",
  "topic": "Powitania",
  "icon": "👋",
  "mnemo": "up = w górę → „co tam na górze?” = co słychać",
  "example": "Hey, Tom! What's up?",
  "added": "2026-09-26"
 },
 {
  "id": "first name",
  "en": "first name",
  "pl": "imię",
  "pron": "[FYRST nejm]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "first = pierwszy — pierwsze imię",
  "example": "My first name is Michal.",
  "added": "2026-09-26"
 },
 {
  "id": "friend",
  "en": "friend",
  "pl": "przyjaciel, znajomy",
  "pron": "[frend]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "fri-END — przyjaciel do samego końca (end)",
  "example": "Tom, this is my friend Anna.",
  "added": "2026-09-26"
 },
 {
  "id": "mr",
  "en": "Mr",
  "pl": "Pan (+ nazwisko)",
  "pron": "[MYS-ter]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "skrót od Mister — jak „Mister Polski”",
  "example": "Hello, Mr Smith.",
  "added": "2026-09-26"
 },
 {
  "id": "mrs",
  "en": "Mrs",
  "pl": "Pani (mężatka, + nazwisko)",
  "pron": "[MY-syz]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "Mrs = więcej liter niż Ms — pani „z mężem” ma dodatkowe „r”",
  "example": "Good morning, Mrs Brown.",
  "added": "2026-09-26"
 },
 {
  "id": "ms",
  "en": "Ms",
  "pl": "Pani (neutralnie, + nazwisko)",
  "pron": "[myz]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "„miz” — krótko i neutralnie, bez informacji o mężu",
  "example": "Goodbye, Ms Green.",
  "added": "2026-09-26"
 },
 {
  "id": "name",
  "en": "name",
  "pl": "imię",
  "pron": "[nejm]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "„nejm” — „na imię”",
  "example": "My name is Tom.",
  "added": "2026-09-25"
 },
 {
  "id": "surname",
  "en": "surname",
  "pl": "nazwisko",
  "pron": "[SYR-nejm]",
  "pos": "rz.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "sur = nad (jak surowy nadzór) + name → „nad-imię” = nazwisko",
  "example": "What's your surname?",
  "added": "2026-09-26"
 },
 {
  "id": "i'm",
  "en": "I'm",
  "pl": "ja jestem (= I am)",
  "pron": "[ajm]",
  "pos": "zaim. + być",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "I am ściśnięte — apostrof zjada „a”",
  "example": "I'm Michal.",
  "added": "2026-09-25"
 },
 {
  "id": "you",
  "en": "you",
  "pl": "ty, wy, pan/pani",
  "pron": "[ju]",
  "pos": "zaim.",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "„ju” — „już ty!”",
  "example": "And you?",
  "added": "2026-09-26"
 },
 {
  "id": "you're",
  "en": "you're",
  "pl": "ty jesteś (= you are)",
  "pron": "[jur]",
  "pos": "zaim. + być",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "you are ściśnięte — apostrof zjada „a” (≠ your = twój)",
  "example": "You're Tom.",
  "added": "2026-09-26"
 },
 {
  "id": "call me mike.",
  "en": "Call me Mike.",
  "pl": "Mów mi Mike.",
  "pron": "[KOL mi majk]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "call = wołać — Call of Duty = „wołanie obowiązku”",
  "example": "I'm Michal. Call me Mike.",
  "added": "2026-09-26"
 },
 {
  "id": "my name is…",
  "en": "My name is…",
  "pl": "Mam na imię…",
  "pron": "[maj NEJM yz]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "my = mój („maj” jak maj — mój miesiąc)",
  "example": "My name is Anna.",
  "added": "2026-09-25"
 },
 {
  "id": "my surname is…",
  "en": "My surname is…",
  "pl": "Mam na nazwisko…",
  "pron": "[maj SYR-nejm yz]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "surname = „nad-imię” = nazwisko",
  "example": "My surname is Smith.",
  "added": "2026-09-26"
 },
 {
  "id": "nice to meet you too.",
  "en": "Nice to meet you too.",
  "pl": "Mnie również miło.",
  "pron": "[najs tu MIT ju TU]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "too = też — „tu też”",
  "example": "Nice to meet you. — Nice to meet you too.",
  "added": "2026-09-26"
 },
 {
  "id": "nice to meet you.",
  "en": "Nice to meet you.",
  "pl": "Miło cię poznać.",
  "pron": "[najs tu MIT ju]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "meet = spotkać — jak „mityng” (meeting) = spotkanie",
  "example": "I'm Tom. Nice to meet you.",
  "added": "2026-09-25"
 },
 {
  "id": "sorry, what's your name again?",
  "en": "Sorry, what's your name again?",
  "pl": "Przepraszam, jak masz na imię? (przypomnij)",
  "pron": "[SO-ri, łots jor NEJM e-GEN]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "again = znowu — „e-gen” jeszcze raz",
  "example": "Sorry, what's your name again?",
  "added": "2026-09-26"
 },
 {
  "id": "this is anna.",
  "en": "This is Anna.",
  "pl": "To jest Anna. (przedstawianie kogoś)",
  "pron": "[DYS yz E-na] ⚠️ th",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "this = to — pokazujesz palcem: „dys!”",
  "example": "Tom, this is Anna.",
  "added": "2026-09-26"
 },
 {
  "id": "what's your name?",
  "en": "What's your name?",
  "pl": "Jak masz na imię?",
  "pron": "[łots jor NEJM]",
  "pos": "zwrot",
  "topic": "Przedstawianie się",
  "icon": "🙋",
  "mnemo": "what = co — „łot to?”",
  "example": "Hi! What's your name?",
  "added": "2026-09-25"
 },
 {
  "id": "bad",
  "en": "bad",
  "pl": "zły, źle",
  "pron": "[bed]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„bed” — złe łóżko = zły",
  "example": "I'm not bad.",
  "added": "2026-09-26"
 },
 {
  "id": "busy",
  "en": "busy",
  "pl": "zajęty",
  "pron": "[BY-zi]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "busi-ness (biznes) — człowiek biznesu jest zajęty",
  "example": "I'm very busy.",
  "added": "2026-09-26"
 },
 {
  "id": "fine",
  "en": "fine",
  "pl": "dobrze, w porządku (samopoczucie)",
  "pron": "[fajn]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„fajn” = fajnie → dobrze",
  "example": "I'm fine.",
  "added": "2026-09-26"
 },
 {
  "id": "good",
  "en": "good",
  "pl": "dobry, dobrze",
  "pron": "[gud]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„gud” jak niemieckie gut = dobry",
  "example": "I'm good, thanks.",
  "added": "2026-09-26"
 },
 {
  "id": "great",
  "en": "great",
  "pl": "świetnie, świetny",
  "pron": "[grejt]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "Aleksander the Great = Wielki → świetny",
  "example": "I'm great!",
  "added": "2026-09-26"
 },
 {
  "id": "happy",
  "en": "happy",
  "pl": "szczęśliwy, zadowolony",
  "pron": "[HE-pi]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "Happy Birthday — szczęśliwych urodzin",
  "example": "I'm happy.",
  "added": "2026-09-26"
 },
 {
  "id": "ok",
  "en": "OK",
  "pl": "w porządku, OK",
  "pron": "[ou-KEJ]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "to samo co po polsku",
  "example": "I'm OK, thanks.",
  "added": "2026-09-26"
 },
 {
  "id": "sad",
  "en": "sad",
  "pl": "smutny",
  "pron": "[sed]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„sed” — sad zimą jest smutny",
  "example": "I'm sad.",
  "added": "2026-09-26"
 },
 {
  "id": "tired",
  "en": "tired",
  "pl": "zmęczony",
  "pron": "[TAJ-erd]",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„tajerd” — „tyrałem” i jestem zmęczony",
  "example": "I'm tired.",
  "added": "2026-09-26"
 },
 {
  "id": "well",
  "en": "well",
  "pl": "dobrze (zdrowo)",
  "pron": "[łel] ⚠️ w",
  "pos": "przym.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "Well done! = dobrze zrobione",
  "example": "I'm very well, thanks.",
  "added": "2026-09-26"
 },
 {
  "id": "very",
  "en": "very",
  "pl": "bardzo",
  "pron": "[WE-ri] ⚠️ v",
  "pos": "przysł.",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„weri” — very good z reklam = bardzo dobry",
  "example": "I'm very tired.",
  "added": "2026-09-26"
 },
 {
  "id": "and you?",
  "en": "And you?",
  "pl": "A ty?",
  "pron": "[end JU]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "and = i → „i ty?”",
  "example": "I'm fine, thanks. And you?",
  "added": "2026-09-26"
 },
 {
  "id": "how are you doing?",
  "en": "How are you doing?",
  "pl": "Jak się masz? / Jak leci?",
  "pron": "[hau ar ju DU-yng]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "doing = robiący → „jak ci idzie robota?”",
  "example": "Hi, Anna! How are you doing?",
  "added": "2026-09-26"
 },
 {
  "id": "how are you?",
  "en": "How are you?",
  "pl": "Jak się masz?",
  "pron": "[hau ar JU]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "how = jak — pies pyta „hau?” jak się masz",
  "example": "Hi, Anna! How are you?",
  "added": "2026-09-26"
 },
 {
  "id": "how's it going?",
  "en": "How's it going?",
  "pl": "Jak leci?",
  "pron": "[hauz yt GOU-yng]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "going = idzie → „jak to idzie?” = jak leci",
  "example": "Hi, Tom! How's it going?",
  "added": "2026-09-26"
 },
 {
  "id": "i'm fine, thanks.",
  "en": "I'm fine, thanks.",
  "pl": "Dobrze, dzięki.",
  "pron": "[ajm fajn, fenks] ⚠️ th",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "fine = fajnie, thanks = dzięki",
  "example": "I'm fine, thanks. And you?",
  "added": "2026-09-26"
 },
 {
  "id": "i'm not very well.",
  "en": "I'm not very well.",
  "pl": "Nie czuję się zbyt dobrze.",
  "pron": "[ajm not WE-ri ŁEL]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "not very well = nie bardzo dobrze",
  "example": "How are you? I'm not very well.",
  "added": "2026-09-26"
 },
 {
  "id": "not bad, thanks.",
  "en": "Not bad, thanks.",
  "pl": "Nieźle, dzięki.",
  "pron": "[not BED, fenks] ⚠️ th",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "not bad = nie-źle → nieźle (dosłownie!)",
  "example": "How's it going? Not bad, thanks.",
  "added": "2026-09-26"
 },
 {
  "id": "not too bad.",
  "en": "Not too bad.",
  "pl": "Całkiem nieźle.",
  "pron": "[not tu BED]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "„nie za źle” → całkiem nieźle",
  "example": "How's it going? Not too bad.",
  "added": "2026-09-26"
 },
 {
  "id": "pretty good, thanks.",
  "en": "Pretty good, thanks.",
  "pl": "Całkiem dobrze, dzięki.",
  "pron": "[PRY-ti gud, fenks] ⚠️ th",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "pretty = ładny → „ładnie dobrze” = całkiem dobrze",
  "example": "How are you? Pretty good, thanks.",
  "added": "2026-09-26"
 },
 {
  "id": "so-so.",
  "en": "So-so.",
  "pl": "Tak sobie.",
  "pron": "[SOU-sou]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "so = tak → „tak-tak” = tak sobie",
  "example": "How are you? — So-so.",
  "added": "2026-09-26"
 },
 {
  "id": "what about you?",
  "en": "What about you?",
  "pl": "A ty? (= And you?)",
  "pron": "[łot e-BAUT ju]",
  "pos": "zwrot",
  "topic": "Samopoczucie",
  "icon": "😊",
  "mnemo": "about = o → „co o tobie?”",
  "example": "I'm fine. What about you?",
  "added": "2026-09-26"
 },
 {
  "id": "excuse me.",
  "en": "Excuse me.",
  "pl": "Przepraszam (żeby zagadać / przejść)",
  "pron": "[yks-KJUZ mi]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "„ekskjuz” — ekskuza = wymówka, usprawiedliwiam się",
  "example": "Excuse me, what's your name?",
  "added": "2026-09-26"
 },
 {
  "id": "no problem.",
  "en": "No problem.",
  "pl": "Nie ma problemu.",
  "pron": "[nou PRO-blem]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "żaden problem — to samo co po polsku",
  "example": "Thanks! No problem.",
  "added": "2026-09-26"
 },
 {
  "id": "of course.",
  "en": "Of course.",
  "pl": "Oczywiście.",
  "pron": "[ow KORS]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "course = kurs — po kursie jesteś pewny → oczywiście",
  "example": "Your name, please? Of course. I'm Tom.",
  "added": "2026-09-26"
 },
 {
  "id": "please.",
  "en": "Please.",
  "pl": "Proszę. (gdy o coś prosisz)",
  "pron": "[pliz]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "„pliiiz” — jak proszące dziecko",
  "example": "Your name, please?",
  "added": "2026-09-26"
 },
 {
  "id": "sorry.",
  "en": "Sorry.",
  "pl": "Przepraszam. (gdy coś zrobisz źle)",
  "pron": "[SO-ri]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "„sori” — jak polskie „sorki!”",
  "example": "Sorry, Tom!",
  "added": "2026-09-26"
 },
 {
  "id": "thank you.",
  "en": "Thank you.",
  "pl": "Dziękuję.",
  "pron": "[FENK ju] ⚠️ th",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "th ≈ dz → thank ≈ „dzięk-uję”",
  "example": "Thank you, Mr Smith.",
  "added": "2026-09-26"
 },
 {
  "id": "thanks a lot!",
  "en": "Thanks a lot!",
  "pl": "Wielkie dzięki!",
  "pron": "[fenks e LOT] ⚠️ th",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "a lot = dużo — samolot (lot) pełen dziękczynień",
  "example": "Thanks a lot, Anna!",
  "added": "2026-09-26"
 },
 {
  "id": "thanks!",
  "en": "Thanks!",
  "pl": "Dzięki!",
  "pron": "[fenks] ⚠️ th",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "krótkie jak „dzięki!”",
  "example": "Thanks, Anna!",
  "added": "2026-09-26"
 },
 {
  "id": "you're welcome.",
  "en": "You're welcome.",
  "pl": "Proszę bardzo. / Nie ma za co.",
  "pron": "[jur ŁEL-kam]",
  "pos": "zwrot",
  "topic": "Grzeczności",
  "icon": "🙏",
  "mnemo": "welcome = mile widziany → „jesteś mile widziany” = nie ma za co",
  "example": "Thank you! — You're welcome.",
  "added": "2026-09-26"
 },
 {
  "id": "bye for now!",
  "en": "Bye for now!",
  "pl": "Na razie! (do następnego razu)",
  "pron": "[baj for NAU]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "for now = na teraz → na razie (dosłownie!)",
  "example": "Bye for now, Tom!",
  "added": "2026-09-26"
 },
 {
  "id": "bye!",
  "en": "Bye!",
  "pl": "Cześć! / Na razie! (pożegnanie)",
  "pron": "[baj]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "„baj” — „bajo!”, pa-pa",
  "example": "Bye, Tom!",
  "added": "2026-09-25"
 },
 {
  "id": "good luck!",
  "en": "Good luck!",
  "pl": "Powodzenia!",
  "pron": "[gud LAK]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "lucky = szczęściarz — luck = szczęście",
  "example": "Goodbye! Good luck!",
  "added": "2026-09-26"
 },
 {
  "id": "good night!",
  "en": "Good night!",
  "pl": "Dobranoc! (tylko na pożegnanie)",
  "pron": "[gud NAJT]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "night = noc — night club = nocny klub",
  "example": "Good night, Tom!",
  "added": "2026-09-26"
 },
 {
  "id": "goodbye!",
  "en": "Goodbye!",
  "pl": "Do widzenia! (razem!)",
  "pron": "[gud-BAJ]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "good + bye sklejone — jedno słowo, jak Hello",
  "example": "Goodbye, Anna!",
  "added": "2026-09-25"
 },
 {
  "id": "have a nice day!",
  "en": "Have a nice day!",
  "pl": "Miłego dnia!",
  "pron": "[hew e najs DEJ]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "day = dzień — „dej” mi miły dzień",
  "example": "Bye! Have a nice day!",
  "added": "2026-09-26"
 },
 {
  "id": "have a nice weekend!",
  "en": "Have a nice weekend!",
  "pl": "Miłego weekendu!",
  "pron": "[hew e najs łik-END]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "week + end = koniec tygodnia — polski „weekend”",
  "example": "Bye! Have a nice weekend!",
  "added": "2026-09-26"
 },
 {
  "id": "see you later!",
  "en": "See you later!",
  "pl": "Do zobaczenia później!",
  "pron": "[si ju LEJ-ter]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "later — przeciągnięte „leeejter” = później",
  "example": "Bye! See you later!",
  "added": "2026-09-25"
 },
 {
  "id": "see you next week!",
  "en": "See you next week!",
  "pl": "Do zobaczenia w przyszłym tygodniu!",
  "pron": "[si ju nekst ŁIK]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "Next! = „Następny, proszę!” — next = następny",
  "example": "Goodbye! See you next week!",
  "added": "2026-09-26"
 },
 {
  "id": "see you soon!",
  "en": "See you soon!",
  "pl": "Do zobaczenia wkrótce!",
  "pron": "[si ju SUN]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "soon = wkrótce — „sun”: słońce wkrótce wstanie",
  "example": "Bye! See you soon!",
  "added": "2026-09-26"
 },
 {
  "id": "see you tomorrow!",
  "en": "See you tomorrow!",
  "pl": "Do zobaczenia jutro!",
  "pron": "[si ju tu-MO-rou]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "to-morrow — „to morze jutro”",
  "example": "Goodbye! See you tomorrow!",
  "added": "2026-09-26"
 },
 {
  "id": "see you!",
  "en": "See you!",
  "pl": "Na razie! / Do zobaczenia!",
  "pron": "[SI ju]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "see = widzieć → „widzimy się”",
  "example": "Bye, Anna! See you!",
  "added": "2026-09-26"
 },
 {
  "id": "take care!",
  "en": "Take care!",
  "pl": "Trzymaj się!",
  "pron": "[tejk KER]",
  "pos": "zwrot",
  "topic": "Pożegnania",
  "icon": "🚪",
  "mnemo": "take = weź + care = troska → „weź troskę” = uważaj na siebie",
  "example": "Bye, Anna! Take care!",
  "added": "2026-09-26"
 },
 {
  "id": "australia",
  "en": "Australia",
  "pl": "Australia",
  "pron": "[os-TREJ-lia]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "to samo, akcent na „TREJ”",
  "example": "Are you from Australia?",
  "added": "2026-09-26"
 },
 {
  "id": "canada",
  "en": "Canada",
  "pl": "Kanada",
  "pron": "[KE-na-da]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Kanada — to samo",
  "example": "I'm from Canada.",
  "added": "2026-09-26"
 },
 {
  "id": "china",
  "en": "China",
  "pl": "Chiny",
  "pron": "[CZAJ-na]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "„czajna” — czajnik i chińska herbata",
  "example": "Are you from China?",
  "added": "2026-09-26"
 },
 {
  "id": "the czech republic",
  "en": "the Czech Republic",
  "pl": "Czechy",
  "pron": "[de czek ry-PA-blyk] ⚠️ th",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Czech = Czech, republic = republika",
  "example": "Are you from the Czech Republic?",
  "added": "2026-09-26"
 },
 {
  "id": "england",
  "en": "England",
  "pl": "Anglia",
  "pron": "[YN-glend]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "ENG-land = kraj Anglików (land = kraj)",
  "example": "I'm from England.",
  "added": "2026-09-26"
 },
 {
  "id": "france",
  "en": "France",
  "pl": "Francja",
  "pron": "[frans]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Francja bez „-ja”",
  "example": "Are you from France?",
  "added": "2026-09-26"
 },
 {
  "id": "germany",
  "en": "Germany",
  "pl": "Niemcy",
  "pron": "[DŻER-me-ni]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Germania — starożytna nazwa Niemiec",
  "example": "Are you from Germany?",
  "added": "2026-09-26"
 },
 {
  "id": "greece",
  "en": "Greece",
  "pl": "Grecja",
  "pron": "[gris]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Greece jak film Grease — „gris”",
  "example": "Are you from Greece?",
  "added": "2026-09-26"
 },
 {
  "id": "india",
  "en": "India",
  "pl": "Indie",
  "pron": "[YN-dia]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "to samo co po polsku",
  "example": "Are you from India?",
  "added": "2026-09-26"
 },
 {
  "id": "ireland",
  "en": "Ireland",
  "pl": "Irlandia",
  "pron": "[AJ-er-lend]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Ire-land — land = kraj → Irlandia",
  "example": "I'm from Ireland.",
  "added": "2026-09-26"
 },
 {
  "id": "italy",
  "en": "Italy",
  "pl": "Włochy",
  "pron": "[Y-ta-li]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Italia bez „-a”",
  "example": "You're from Italy.",
  "added": "2026-09-26"
 },
 {
  "id": "japan",
  "en": "Japan",
  "pl": "Japonia",
  "pron": "[dże-PEN]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Japonia bez „-onia”",
  "example": "I'm from Japan.",
  "added": "2026-09-26"
 },
 {
  "id": "mexico",
  "en": "Mexico",
  "pl": "Meksyk",
  "pron": "[MEK-sy-kou]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "to samo co po polsku",
  "example": "I'm from Mexico.",
  "added": "2026-09-26"
 },
 {
  "id": "the netherlands",
  "en": "the Netherlands",
  "pl": "Holandia",
  "pron": "[de NE-der-lendz] ⚠️ th",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "nether = niski + lands → „Niderlandy” = niskie kraje",
  "example": "I'm from the Netherlands.",
  "added": "2026-09-26"
 },
 {
  "id": "norway",
  "en": "Norway",
  "pl": "Norwegia",
  "pron": "[NOR-łej] ⚠️ w",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Nor-way = „północna droga”",
  "example": "Are you from Norway?",
  "added": "2026-09-26"
 },
 {
  "id": "poland",
  "en": "Poland",
  "pl": "Polska",
  "pron": "[POU-lend]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Po-land = kraj Polan (land = kraj)",
  "example": "I'm from Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "portugal",
  "en": "Portugal",
  "pl": "Portugalia",
  "pron": "[POR-czu-gl]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "prawie jak po polsku",
  "example": "I'm from Portugal.",
  "added": "2026-09-26"
 },
 {
  "id": "scotland",
  "en": "Scotland",
  "pl": "Szkocja",
  "pron": "[SKOT-lend]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Scot-land = kraj Szkotów",
  "example": "I'm from Scotland.",
  "added": "2026-09-26"
 },
 {
  "id": "spain",
  "en": "Spain",
  "pl": "Hiszpania",
  "pron": "[spejn]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Spa-in → Spa-nish: te same litery",
  "example": "You're from Spain.",
  "added": "2026-09-26"
 },
 {
  "id": "sweden",
  "en": "Sweden",
  "pl": "Szwecja",
  "pron": "[SŁI-dn]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Swe-den → Szwe-cja: to samo „Sw”",
  "example": "I'm from Sweden.",
  "added": "2026-09-26"
 },
 {
  "id": "turkey",
  "en": "Turkey",
  "pl": "Turcja",
  "pron": "[TYR-ki]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "⚠️ turkey (mała litera) = indyk!",
  "example": "I'm from Turkey.",
  "added": "2026-09-26"
 },
 {
  "id": "the uk",
  "en": "the UK",
  "pl": "Wielka Brytania",
  "pron": "[de ju-KEJ] ⚠️ th",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "United Kingdom = Zjednoczone Królestwo — z the",
  "example": "I'm from the UK.",
  "added": "2026-09-26"
 },
 {
  "id": "ukraine",
  "en": "Ukraine",
  "pl": "Ukraina",
  "pron": "[ju-KREJN]",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Ukraina bez końcowego „a”",
  "example": "Are you from Ukraine?",
  "added": "2026-09-26"
 },
 {
  "id": "the usa",
  "en": "the USA",
  "pl": "USA",
  "pron": "[de ju-es-EJ] ⚠️ th",
  "pos": "rz.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "the United States — Stany „te” zjednoczone, zawsze z the",
  "example": "I'm from the USA.",
  "added": "2026-09-26"
 },
 {
  "id": "american",
  "en": "American",
  "pl": "amerykański / Amerykanin",
  "pron": "[e-ME-ry-ken]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Ameryka + -n",
  "example": "I'm American.",
  "added": "2026-09-26"
 },
 {
  "id": "australian",
  "en": "Australian",
  "pl": "australijski / Australijczyk",
  "pron": "[os-TREJ-lien]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Australia + -n",
  "example": "Are you Australian?",
  "added": "2026-09-26"
 },
 {
  "id": "british",
  "en": "British",
  "pl": "brytyjski / Brytyjczyk",
  "pron": "[BRY-tysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Brit-ania → Brit-ish",
  "example": "Are you British?",
  "added": "2026-09-26"
 },
 {
  "id": "canadian",
  "en": "Canadian",
  "pl": "kanadyjski / Kanadyjczyk",
  "pron": "[ke-NEJ-dien]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Kanada + -ian",
  "example": "I'm Canadian.",
  "added": "2026-09-26"
 },
 {
  "id": "chinese",
  "en": "Chinese",
  "pl": "chiński / Chińczyk",
  "pron": "[czaj-NIZ]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "China → Chin-ese",
  "example": "Are you Chinese?",
  "added": "2026-09-26"
 },
 {
  "id": "czech",
  "en": "Czech",
  "pl": "czeski / Czech",
  "pron": "[czek]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "„czek” jak czek w banku",
  "example": "I'm Czech.",
  "added": "2026-09-26"
 },
 {
  "id": "dutch",
  "en": "Dutch",
  "pl": "holenderski / Holender",
  "pron": "[dacz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "⚠️ pułapka: Dutch = Holender, NIE Niemiec (Deutsch)",
  "example": "Are you Dutch?",
  "added": "2026-09-26"
 },
 {
  "id": "english",
  "en": "English",
  "pl": "angielski / Anglik",
  "pron": "[YN-glysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "England → Engl-ish",
  "example": "Are you English?",
  "added": "2026-09-26"
 },
 {
  "id": "french",
  "en": "French",
  "pl": "francuski / Francuz",
  "pron": "[frencz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "French fries = frytki po francusku",
  "example": "Are you French?",
  "added": "2026-09-26"
 },
 {
  "id": "german",
  "en": "German",
  "pl": "niemiecki / Niemiec",
  "pron": "[DŻER-men]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Germany bez -y",
  "example": "No, I'm not German.",
  "added": "2026-09-26"
 },
 {
  "id": "greek",
  "en": "Greek",
  "pl": "grecki / Grek",
  "pron": "[grik]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Greek yogurt = jogurt grecki",
  "example": "I'm Greek.",
  "added": "2026-09-26"
 },
 {
  "id": "indian",
  "en": "Indian",
  "pl": "indyjski / Hindus",
  "pron": "[YN-dien]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "India → Ind-ian",
  "example": "You're Indian.",
  "added": "2026-09-26"
 },
 {
  "id": "irish",
  "en": "Irish",
  "pl": "irlandzki / Irlandczyk",
  "pron": "[AJ-rysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Irish coffee — kawa po irlandzku",
  "example": "No, I'm not Irish.",
  "added": "2026-09-26"
 },
 {
  "id": "italian",
  "en": "Italian",
  "pl": "włoski / Włoch",
  "pron": "[y-TE-lien]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Italy → Ital-ian (jak Italian pizza)",
  "example": "You're Italian.",
  "added": "2026-09-26"
 },
 {
  "id": "japanese",
  "en": "Japanese",
  "pl": "japoński / Japończyk",
  "pron": "[dże-pe-NIZ]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Japan → Japan-ese",
  "example": "I'm not Japanese.",
  "added": "2026-09-26"
 },
 {
  "id": "mexican",
  "en": "Mexican",
  "pl": "meksykański / Meksykanin",
  "pron": "[MEK-sy-ken]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Mexico → Mexic-an",
  "example": "You're Mexican.",
  "added": "2026-09-26"
 },
 {
  "id": "norwegian",
  "en": "Norwegian",
  "pl": "norweski / Norweg",
  "pron": "[nor-ŁI-dżen]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Norw-ay → Norw-egian",
  "example": "Are you Norwegian?",
  "added": "2026-09-26"
 },
 {
  "id": "polish",
  "en": "Polish",
  "pl": "polski / Polak",
  "pron": "[POU-lysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Pol-and → Pol-ish ⚠️ polish małą literą = polerować!",
  "example": "I'm Polish.",
  "added": "2026-09-26"
 },
 {
  "id": "portuguese",
  "en": "Portuguese",
  "pl": "portugalski / Portugalczyk",
  "pron": "[por-czu-GIZ]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "końcówka -ese jak w Chinese",
  "example": "I'm not Portuguese.",
  "added": "2026-09-26"
 },
 {
  "id": "scottish",
  "en": "Scottish",
  "pl": "szkocki / Szkot",
  "pron": "[SKO-tysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Scotch whisky — szkocka",
  "example": "I'm not Scottish.",
  "added": "2026-09-26"
 },
 {
  "id": "spanish",
  "en": "Spanish",
  "pl": "hiszpański / Hiszpan",
  "pron": "[SPE-nysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Spain → Span-ish",
  "example": "You're Spanish.",
  "added": "2026-09-26"
 },
 {
  "id": "swedish",
  "en": "Swedish",
  "pl": "szwedzki / Szwed",
  "pron": "[SŁI-dysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Swed-en → Swed-ish",
  "example": "You're Swedish.",
  "added": "2026-09-26"
 },
 {
  "id": "turkish",
  "en": "Turkish",
  "pl": "turecki / Turek",
  "pron": "[TYR-kysz]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Turk-ey → Turk-ish (Turkish coffee)",
  "example": "Are you Turkish?",
  "added": "2026-09-26"
 },
 {
  "id": "ukrainian",
  "en": "Ukrainian",
  "pl": "ukraiński / Ukrainiec",
  "pron": "[ju-KREJ-nien]",
  "pos": "przym.",
  "topic": "Kraje i narodowości",
  "icon": "🌍",
  "mnemo": "Ukraine → Ukrain-ian",
  "example": "I'm Ukrainian.",
  "added": "2026-09-26"
 },
 {
  "id": "capital",
  "en": "capital",
  "pl": "stolica",
  "pron": "[KE-py-tl]",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "kapitał — w stolicy są pieniądze",
  "example": "Warsaw is a capital.",
  "added": "2026-09-26"
 },
 {
  "id": "city",
  "en": "city",
  "pl": "miasto",
  "pron": "[SY-ti]",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "Manchester City — City = miasto",
  "example": "Warsaw is a city.",
  "added": "2026-09-26"
 },
 {
  "id": "country",
  "en": "country",
  "pl": "kraj",
  "pron": "[KAN-tri]",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "muzyka country = muzyka z (wiejskiego) kraju",
  "example": "Poland is a country.",
  "added": "2026-09-26"
 },
 {
  "id": "nationality",
  "en": "nationality",
  "pl": "narodowość",
  "pron": "[ne-sze-NE-ly-ti]",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "nacjonalność → narodowość (nation = naród)",
  "example": "What's your nationality?",
  "added": "2026-09-26"
 },
 {
  "id": "town",
  "en": "town",
  "pl": "miasteczko",
  "pron": "[taun]",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "downtown = centrum miasta",
  "example": "I'm from a small town.",
  "added": "2026-09-26"
 },
 {
  "id": "village",
  "en": "village",
  "pl": "wieś",
  "pron": "[WY-lydż] ⚠️ v",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "„wila” na wsi",
  "example": "I'm from a village.",
  "added": "2026-09-26"
 },
 {
  "id": "warsaw",
  "en": "Warsaw",
  "pl": "Warszawa",
  "pron": "[ŁOR-soł] ⚠️ w",
  "pos": "rz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "W czytaj jak „ł” → „Łorsoł”",
  "example": "I'm from Warsaw.",
  "added": "2026-09-26"
 },
 {
  "id": "come from",
  "en": "come from",
  "pl": "pochodzić z",
  "pron": "[kam from]",
  "pos": "cz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "come = przyjść → „przychodzę z Polski”",
  "example": "I come from Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "live",
  "en": "live",
  "pl": "mieszkać, żyć",
  "pron": "[lyw]",
  "pos": "cz.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "koncert live = na żywo → żyć, mieszkać",
  "example": "I live in Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "big",
  "en": "big",
  "pl": "duży",
  "pron": "[byg]",
  "pos": "przym.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "Big Mac — duży burger",
  "example": "Warsaw is big.",
  "added": "2026-09-26"
 },
 {
  "id": "small",
  "en": "small",
  "pl": "mały",
  "pron": "[smol]",
  "pos": "przym.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "„smol” — mała kropla smoły",
  "example": "I'm from a small town.",
  "added": "2026-09-26"
 },
 {
  "id": "from",
  "en": "from",
  "pl": "z (skąd)",
  "pron": "[from]",
  "pos": "przyim.",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "„from A to B” = z A do B",
  "example": "I'm from Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "i come from poland.",
  "en": "I come from Poland.",
  "pl": "Pochodzę z Polski.",
  "pron": "[aj kam from POU-lend]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "= I'm from Poland",
  "example": "I come from Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "i live in poland.",
  "en": "I live in Poland.",
  "pl": "Mieszkam w Polsce.",
  "pron": "[aj lyw yn POU-lend]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "live = mieszkać (na żywo)",
  "example": "I'm Polish. I live in Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "i'm from a small town.",
  "en": "I'm from a small town.",
  "pl": "Jestem z małego miasteczka.",
  "pron": "[ajm from e smol TAUN]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "small = mały + town = miasteczko",
  "example": "I'm from a small town in Poland.",
  "added": "2026-09-26"
 },
 {
  "id": "what's your nationality?",
  "en": "What's your nationality?",
  "pl": "Jakiej jesteś narodowości?",
  "pron": "[łots jor ne-sze-NE-ly-ti]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "nationality = nacjonalność = narodowość",
  "example": "What's your nationality? I'm Polish.",
  "added": "2026-09-26"
 },
 {
  "id": "where are you from?",
  "en": "Where are you from?",
  "pl": "Skąd jesteś?",
  "pron": "[łer ar ju FROM]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "where = gdzie — „łer ty łazisz?”",
  "example": "Hi! Where are you from?",
  "added": "2026-09-26"
 },
 {
  "id": "where in poland?",
  "en": "Where in Poland?",
  "pl": "Skąd dokładnie w Polsce?",
  "pron": "[łer yn POU-lend]",
  "pos": "zwrot",
  "topic": "Pochodzenie i miejsce zamieszkania",
  "icon": "🏙️",
  "mnemo": "in = w → „gdzie w Polsce?”",
  "example": "I'm from Poland. Where in Poland?",
  "added": "2026-09-26"
 },
 {
  "id": "can you repeat that, please?",
  "en": "Can you repeat that, please?",
  "pl": "Możesz to powtórzyć?",
  "pron": "[ken ju ry-PIT det, pliz] ⚠️ th",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "repeat = repetować, powtarzać",
  "example": "Pardon? Can you repeat that, please?",
  "added": "2026-09-26"
 },
 {
  "id": "can you speak slowly, please?",
  "en": "Can you speak slowly, please?",
  "pl": "Możesz mówić wolniej?",
  "pron": "[ken ju spik SLOU-li, pliz]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "slow = wolny (slow food), speak → speaker (głośnik)",
  "example": "Sorry, I don't understand. Can you speak slowly, please?",
  "added": "2026-09-26"
 },
 {
  "id": "cool!",
  "en": "Cool!",
  "pl": "Super! / Fajnie!",
  "pron": "[kul]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "cool = chłodny → „na chłodno, spoko” = super",
  "example": "I'm from Canada. Cool!",
  "added": "2026-09-26"
 },
 {
  "id": "do you speak english?",
  "en": "Do you speak English?",
  "pl": "Mówisz po angielsku?",
  "pron": "[du ju spik YN-glysz]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "speak = mówić — speaker = głośnik",
  "example": "Excuse me, do you speak English?",
  "added": "2026-09-26"
 },
 {
  "id": "me too.",
  "en": "Me too.",
  "pl": "Ja też.",
  "pron": "[mi TU]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "too = też — „tu też”",
  "example": "I'm Polish. Me too.",
  "added": "2026-09-26"
 },
 {
  "id": "my english is not very good.",
  "en": "My English is not very good.",
  "pl": "Mój angielski nie jest zbyt dobry.",
  "pron": "[maj YN-glysz yz not WE-ri GUD]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "not very good = nie bardzo dobry",
  "example": "Sorry, my English is not very good.",
  "added": "2026-09-26"
 },
 {
  "id": "pardon?",
  "en": "Pardon?",
  "pl": "Słucham? (nie dosłyszałem)",
  "pron": "[PAR-dn]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "„pardon” — jak w polskim „pardon!”",
  "example": "Pardon? What's your name?",
  "added": "2026-09-26"
 },
 {
  "id": "really?",
  "en": "Really?",
  "pl": "Naprawdę?",
  "pron": "[RI-li]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "real = prawdziwy (Real Madryt) → naprawdę?",
  "example": "I'm from Spain. Really?",
  "added": "2026-09-26"
 },
 {
  "id": "sorry, i don't understand.",
  "en": "Sorry, I don't understand.",
  "pl": "Przepraszam, nie rozumiem.",
  "pron": "[SO-ri, aj dount an-der-STEND]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "under-stand = „stać pod” — ogarniam od spodu = rozumiem",
  "example": "Sorry, I don't understand. Pardon?",
  "added": "2026-09-26"
 },
 {
  "id": "yes, i am. / no, i'm not.",
  "en": "Yes, I am. / No, I'm not.",
  "pl": "Tak, jestem. / Nie, nie jestem.",
  "pron": "[jes aj EM / nou ajm NOT]",
  "pos": "zwrot",
  "topic": "Reagowanie w rozmowie",
  "icon": "💬",
  "mnemo": "„Tak” = pełne I am · „Nie” = skrót + not",
  "example": "Are you Polish? Yes, I am.",
  "added": "2026-09-26"
 }
];
