// Ikony słówek (assets/words/, z Desktop/ikony_do_aplikacji/kraje) — kraj i narodowość zwykle mają tę samą;
// Wielka Brytania (autobus) ≠ Anglia (Big Ben), Szwecja ≠ szwedzki (drakkar), żeby się nie myliły.
// Klucz = id słowa (małe litery), wartość = plik assets/words/<nazwa>.png.
// Ikony dodane w panelu dewelopera są osobno: js/word-icons-extra.js.
window.WORD_ICONS = {
  'australia': 'australia',
  'australian': 'australia',
  'canada': 'kanada',
  'canadian': 'kanada',
  'china': 'chiny',
  'chinese': 'chiny',
  'india': 'indie',
  'indian': 'indie',
  'russia': 'rosja',
  'russian': 'rosja',
  'south africa': 'rpa',
  'south african': 'rpa',
  'brazil': 'brazylia',
  'brazilian': 'brazylia',
  'argentina': 'argentyna',
  'argentinian': 'argentyna',
  'mexico': 'meksyk',
  'mexican': 'meksyk',
  'egypt': 'egipt',
  'egyptian': 'egipt',
  'saudi arabia': 'arabia_saudyjska',
  'saudi': 'arabia_saudyjska',
  'turkey': 'turcja',
  'turkish': 'turcja',
  'germany': 'niemcy',
  'german': 'niemcy',
  'france': 'francja',
  'french': 'francja',
  'england': 'anglia',
  'english': 'anglia',
  'italy': 'wlochy',
  'italian': 'wlochy',
  'spain': 'hiszpania',
  'spanish': 'hiszpania',
  'poland': 'polska',
  'polish': 'polska',
  'sweden': 'szwecja',
  'the netherlands': 'holandia',
  'dutch': 'holandia',
  'belgium': 'belgia',
  'belgian': 'belgia',
  'denmark': 'dania',
  'danish': 'dania',
  'norway': 'norwegia',
  'norwegian': 'norwegia',
  'finland': 'finlandia',
  'finnish': 'finlandia',
  'the czech republic': 'czechy',
  'czech': 'czechy',
  'greece': 'grecja',
  'greek': 'grecja',
  'ireland': 'irlandia',
  'irish': 'irlandia',
  'japan': 'japonia',
  'japanese': 'japonia',
  'portugal': 'portugalia',
  'portuguese': 'portugalia',
  'scotland': 'szkocja',
  'scottish': 'szkocja',
  'ukraine': 'ukraina',
  'ukrainian': 'ukraina',
  'the usa': 'usa',
  'american': 'usa',
  'the uk': 'wielka_brytania_autobus',
  'british': 'wielka_brytania_autobus',
  'swedish': 'szwecja_drakkar',
  'switzerland': 'szwajcaria',
  'swiss': 'szwajcaria',
  'austria': 'austria',
  'austrian': 'austria',
  'south korea': 'korea_poludniowa',
  'korean': 'korea_poludniowa',
  'wales': 'walia',
  'welsh': 'walia',
  'hungary': 'wegry',
  'hungarian': 'wegry',
  'croatia': 'chorwacja',
  'croatian': 'chorwacja',
  'iceland': 'islandia',
  'icelandic': 'islandia',
  'slovakia': 'slowacja',
  'slovak': 'slowacja',
  'slovenia': 'slowenia',
  'slovenian': 'slowenia',
  'romania': 'rumunia',
  'romanian': 'rumunia',
  'bulgaria': 'bulgaria',
  'bulgarian': 'bulgaria',
  'serbia': 'serbia',
  'serbian': 'serbia',
  'lithuania': 'litwa',
  'lithuanian': 'litwa',
  'latvia': 'lotwa',
  'latvian': 'lotwa',
  'estonia': 'estonia',
  'estonian': 'estonia',
  'belarus': 'bialorus',
  'belarusian': 'bialorus',
  'thailand': 'tajlandia',
  'thai': 'tajlandia',
  'the uae': 'zea_dubaj',
  'emirati': 'zea_dubaj',
  'vietnam': 'wietnam',
  'vietnamese': 'wietnam',
  'indonesia': 'indonezja',
  'indonesian': 'indonezja',
  'the philippines': 'filipiny',
  'filipino': 'filipiny',
  'cuba': 'kuba',
  'cuban': 'kuba',
  'chile': 'chile',
  'chilean': 'chile',
  'colombia': 'kolumbia',
  'colombian': 'kolumbia',
  'morocco': 'maroko',
  'moroccan': 'maroko',
  'new zealand': 'nowa_zelandia',
  'new zealander': 'nowa_zelandia',
  'israel': 'izrael',
  'israeli': 'izrael',
  'georgia': 'gruzja',
  'georgian': 'gruzja',
  'iran': 'iran',
  'iranian': 'iran',
  'pakistan': 'pakistan',
  'pakistani': 'pakistan',
  'nigeria': 'nigeria',
  'nigerian': 'nigeria',
  'africa': 'afryka',
  'african': 'afryka',
  'asia': 'azja',
  'asian': 'azja',
  'europe': 'europa',
  'european': 'europa',
  'north america': 'ameryka_polnocna',
  'north american': 'ameryka_polnocna',
  'south america': 'ameryka_poludniowa',
  'south american': 'ameryka_poludniowa',
  'continent': 'kontynent',
  'warsaw': 'warszawa',
  'capital': 'stolica',
  'city': 'miasto',
  'town': 'miasteczko',
  'village': 'wies',
  'country': 'kraj',
  'nationality': 'narodowosc',
  // przedstawianie się (Desktop/ikony_do_aplikacji)
  'first name': 'first_name', 'friend': 'friend', 'mr': 'mr', 'mrs': 'mrs', 'ms': 'ms', 'name': 'name', 'surname': 'surname',
  "i'm": 'im', 'you': 'you', "you're": 'youre',
};
